services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
    #  - VIRTUAL_HOST=${FQDN}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY} #replace with a secure key to encrypt your Tesla API tokens
      - DATABASE_USER=teslamate
      - DATABASE_PASS=${POSTGRES_PASSWORD} #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - TZ=Europe/Zurich
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:18-trixie
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} #insert your secure database password!
      - POSTGRES_DB=teslamate
      - TZ=Europe/Zurich
    volumes:
      - teslamate-db:/var/lib/postgresql

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=${POSTGRES_PASSWORD} #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - TZ=Europe/Zurich
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SERVER_DOMAIN=${DOMAIN}
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_CSRF_TRUSTED_ORIGINS=${DOMAIN}
      - GF_AUTH_AZUREAD_NAME='Entra ID'
      - GF_AUTH_AZUREAD_ENABLED=true
      - GF_AUTH_AZUREAD_ALLOW_SIGN_UP=true
      - GF_AUTH_AZUREAD_AUTO_LOGIN=false
      - GF_AUTH_AZUREAD_CLIENT_AUTHENTICATION=${GF_AUTH_AZUREAD_CLIENT_AUTHENTICATION}
      - GF_AUTH_AZUREAD_CLIENT_ID=${GF_AUTH_AZUREAD_CLIENT_ID}
      - GF_AUTH_AZUREAD_CLIENT_SECRET=${GF_AUTH_AZUREAD_CLIENT_SECRET}
      - GF_AUTH_AZUREAD_SCOPES='openid email profile'
      #- GF_AUTH_AZUREAD_ALLOWED_DOMAINS=''
      #- GF_AUTH_AZUREAD_ALLOWED_GROUPS=''
      #- GF_AUTH_AZUREAD_ALLOWED_ORGANIZATIONS=${GF_AUTH_AZUREAD_ALLOWED_ORGANIZATIONS}
      - GF_AUTH_AZUREAD_ROLE_ATTRIBUTE_STRICT=false
      - GF_AUTH_AZUREAD_SKIP_ORG_ROLE_SYNC=false
      - GF_AUTH_AZUREAD_ALLOW_ASSIGN_GRAFANA_ADMIN=true
      
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
      - teslamate-grafana-config:/etc/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  teslamate-grafana-config:
  mosquitto-conf:
  mosquitto-data:
